demo_configuration_form:
  path: /demosymfonyform/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\DemoSymfonyForm\Controller\DemoConfigurationController::index'
    # Needed to work with tab system
    _legacy_controller: AdminDemoSymfonyForm
    _legacy_link: AdminDemoSymfonyForm

demo_configuration_multiple_forms:
  path: /demosymfonyform/configurationMultipleForms
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\Module\DemoSymfonyForm\Controller\DemoConfigurationMultipleFormsController::index'
    _legacy_controller: AdminDemoSymfonyFormMultipleForms
    _legacy_link: AdminDemoSymfonyFormMultipleForms

create_shipping_rule:
  path: /admin/demo-configuration-multiple-forms/create-shipping-rule
  methods: [POST]
  defaults:
    _controller: 'PrestaShop\Module\DemoSymfonyForm\Controller\DemoConfigurationMultipleFormsController::createShippingRule'
update_shipping_rule:
  path: /admin/demo-configuration-multiple-forms/update-shipping-rule
  methods: [PUT]
  defaults:
    _controller: 'PrestaShop\Module\DemoSymfonyForm\Controller\DemoConfigurationMultipleFormsController::updateShippingRule'

delete_shipping_rule:
  path: /admin/demo-configuration-multiple-forms/delete-shipping-rule
  methods: [DELETE]
  defaults:
    _controller: 'PrestaShop\Module\DemoSymfonyForm\Controller\DemoConfigurationMultipleFormsController::deleteShippingRule'